name: Alter Prompt

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CLOUDFLARE_ACCESS_TOKEN:
        required: true
      CLOUDFLARE_USER_ID:
        required: true
      YEEHAW_ALTER_ANIMAL_PROMPT_TOKEN:
        required: true

jobs:
  update_animal_prompt:
    runs-on: ubuntu-latest

    steps:
      - name: Generate new animal prompt using random style and habitat
        run: |
          set -e
          
          # Convert comma-separated lists to arrays
          IFS=',' read -ra STYLES <<< "${{ vars.IMAGE_STYLE }}"
          IFS=',' read -ra HABITATS <<< "${{ vars.ANIMAL_HABITAT }}"
          IFS=',' read -ra CLASS <<< "${{ vars.ANIMAL_CLASS }}"
          IFS=',' read -ra SIMILAR <<< "${{ vars.ANIMAL_SIMILAR_ANIMALS }}"

          # Select random style and habitat
          RANDOM_STYLE=$(printf "%s\n" "${STYLES[@]}" | shuf -n 1)
          RANDOM_HABITAT=$(printf "%s\n" "${HABITATS[@]}" | shuf -n 1)
          RANDOM_CLASS=$(printf "%s\n" "${CLASS[@]}" | shuf -n 1)
          RANDOM_ANIMAL=$(printf "%s\n" "${SIMILAR[@]}" | shuf -n 1)

          # Generate prompt
          TIMESTAMP=$(date +%s)
          
          # PROMPT="Create an image of a beautiful fantastical creature that lives in a $RANDOM_HABITAT. Image of the style: $RANDOM_STYLE."
          # PROMPT="Create an image of an imaginative and otherworldly creature. It belongs to the class of $RANDOM_CLASS. Please, do not create an image with an empty background. Show the animal's habitat, and show how the animal interacts with it. "
          PROMPT="Create a detailed scene featuring a fantastical creature in its natural environment. The creature is a $RANDOM_CLASS and lives in a $RANDOM_HABITAT. Show the creature interacting with or moving through its habitat. The image should depict not just the creature but also its surroundings — plants, terrain, atmosphere — as part of a coherent and vivid landscape."

          echo "Generated Prompt: $PROMPT"
          echo "PROMPT_ESCAPED=$PROMPT" >> $GITHUB_ENV

      - name: Update ANIMAL_PROMPT variable in GitHub repository
        env:
          YEEHAW_ALTER_ANIMAL_PROMPT_TOKEN: ${{ secrets.YEEHAW_ALTER_ANIMAL_PROMPT_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          curl --location --request PATCH "https://api.github.com/repos/$REPO/actions/variables/ANIMAL_PROMPT" \
            --header 'Accept: application/vnd.github+json' \
            --header "Authorization: Bearer $YEEHAW_ALTER_ANIMAL_PROMPT_TOKEN" \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            --header 'Content-Type: application/json' \
            --data "$(jq -n --arg value "$PROMPT_ESCAPED" '{name: "ANIMAL_PROMPT", value: $value}')"
