name: Alter Animal Prompt

on:
  schedule:
    - cron: '0 7 * * *'  # Todos los días a las 7:00 UTC
  workflow_dispatch:

jobs:
  update-prompt:
    runs-on: ubuntu-latest

    steps:
      - name: Call Llama to get a new image prompt generator
        id: llama_prompt
        run: |
          RESPONSE=$(curl -s --location 'https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_USER_ID }}/ai/run/@cf/meta/llama-4-scout-17b-16e-instruct' \
            --header "Authorization: Bearer ${{ secrets.CLOUDFLARE_ACCESS_TOKEN }}" \
            --header 'Content-Type: application/json' \
            --data '{
              "messages": [
                { "role": "system", "content": "You are a creative assistant." },
                { "role": "user", "content": "Invent a totally unique, colorful, and imaginative prompt for generating an image of a fantastic creature. The image should depict an animal that does not exist, and the style should be artistic and visually appealing, not realistic." }
              ]
            }')
      
          PROMPT=$(echo "$RESPONSE" | jq -r '.result.response')
          echo "Generated Prompt: $PROMPT"
      
          ESCAPED_PROMPT=$(jq -Rn --arg val "$PROMPT" '{"name":"PROMPT_PROMPT", "value": $val}')
      
          curl --location --request PATCH "https://api.github.com/repos/${{ github.repository }}/actions/variables/PROMPT_PROMPT" \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Content-Type: application/json" \
            --data "$ESCAPED_PROMPT"


      - name: Update PROMPT_PROMPT repo variable
        run: |
          curl --location --request PATCH "https://api.github.com/repos/${{ github.repository }}/actions/variables/PROMPT_PROMPT" \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${{ secrets.YEEHAW_ALTER_ANIMAL_PROMPT_TOKEN }}" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Content-Type: application/json" \
            --data "{\"name\":\"PROMPT_PROMPT\",\"value\":${{ env.PROMPT_ESCAPED }}}"
