name: Update Prompt Prompt

on:
  schedule:
    - cron: '0 6 * * *' # Cada día a las 06:00 UTC
  workflow_dispatch:

jobs:
  update_prompt_prompt:
    runs-on: ubuntu-latest

    steps:
      - name: Call Llama to get a new image prompt generator
        env:
          CLOUDFLARE_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_ACCESS_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_USER_ID }}
        run: |
          RESPONSE=$(curl -s https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_USER_ID/ai/run/@cf/meta/llama-4-scout-17b-16e-instruct \
            -X POST \
            -H "Authorization: Bearer $CLOUDFLARE_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "messages": [
                { "role": "system", "content": "You are a creative assistant." },
                { "role": "user", "content": "Give me a prompt to generate a non-existent animal. Be as imaginative and crazy as possible." }
              ]
            }')

          echo "$RESPONSE"

          PROMPT=$(echo "$RESPONSE" | jq -r '.result.response' | tr -d "'")
          PROMPT_ESCAPED=$(printf '%s\n' "$PROMPT" | jq -aRs .)

          echo "PROMPT=$PROMPT" >> $GITHUB_ENV
          echo "PROMPT_ESCAPED=$PROMPT_ESCAPED" >> $GITHUB_ENV

      - name: Update PROMPT_PROMPT variable in GitHub repository
        env:
          GH_TOKEN: ${{ secrets.YEEHAW_ALTER_ANIMAL_PROMPT_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          curl --location --request PATCH "https://api.github.com/repos/jmtdev0/AnAInimalADay/actions/variables/PROMPT_PROMPT" \
            --header 'Accept: application/vnd.github+json' \
            --header "Authorization: Bearer $YEEHAW_ALTER_ANIMAL_PROMPT_TOKEN" \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            --header 'Content-Type: application/json' \
            --data "{\"name\":\"PROMPT_PROMPT\",\"value\":${PROMPT_ESCAPED}}"
